USE FIRSTDATABASE;
SELECT * FROM BRANCH2;

-- CONTINUE
DELIMITER $$
CREATE PROCEDURE INSERTBRANCH(
	IN ID INT,
    IN B_NAME VARCHAR(10),
    IN ADDR VARCHAR(10)    
)
BEGIN						  -- SQLSTATE '23000' 
	DECLARE CONTINUE HANDLER FOR 1062 -- ERROR CODE for specific error
    -- COMMON
    /* -SQLEXCEPTION 
	   - SQLWARNING 
       - NOT FOUND */
	begin
		SELECT CONCAT('DUPLICATE KEY ',ID,' CANNOT INSERT INTO BRANCH2 TABLE');
	end;
	INSERT INTO BRANCH2 VALUES(ID,B_NAME,ADDR);
    SELECT * FROM BRANCH2;
END $$
DELIMITER ;

CALL INSERTBRANCH(1,'MUMBAI','WANKADE');
DROP PROCEDURE IF EXISTS INSERTBRANCH;

-- EXIT ----------------------------------------------------------------
DELIMITER $$
CREATE PROCEDURE INSERTBRANCH1(
	IN ID INT,
    IN B_NAME VARCHAR(10),
    IN ADDR VARCHAR(10)
)
BEGIN
	DECLARE DUPLICATEINSERT CONDITION FOR 1062;
	DECLARE EXIT HANDLER FOR DUPLICATEINSERT
    BEGIN
		SELECT CONCAT('DUPLICATE KEY ',ID,' CANNOT BE INSERTED INTO BRANCH2 TABLE');
    END;
    INSERT INTO BRANCH2 VALUES(ID,B_NAME,ADDR);
    SELECT * FROM BRANCH2;
END $$
DELIMITER ;

CALL INSERTBRANCH1(1,'KODAIKANAL','LAKE');