-- FUNCTIONS
USE FIRSTDATABASE;
SELECT * FROM EMPLOYEE4;
SELECT * FROM BRANCH2;

SELECT NAME,BRANCH_ID FROM EMPLOYEE4;

SHOW FUNCTION STATUS;

SELECT NAME,GETBRANCH_ADDR(BRANCH_ID) AS FULL_ADDRESS FROM EMPLOYEE4;
DROP FUNCTION IF EXISTS GETBRANCH_ADDR; 

DELIMITER $$
CREATE FUNCTION GETBRANCH_ADDR(ID INT)
RETURNS VARCHAR(50)
DETERMINISTIC
BEGIN
	DECLARE FULL_ADDRESS VARCHAR(50);
	SELECT CONCAT(ADDRESS,'    ',BRANCH_NAME) INTO FULL_ADDRESS
    FROM BRANCH2
    WHERE BRANCH_ID = ID;
    RETURN FULL_ADDRESS;
END $$
DELIMITER ;