USE FIRSTDATABASE;
SELECT * FROM BRANCH2;

-- IF
DELIMITER $$
CREATE PROCEDURE GETSTATE(
	IN ID INT
)
BEGIN
	IF ID=1 OR ID=2 THEN
		SELECT 'TAMILNADU' AS STATE;
    ELSEIF ID=3 THEN
		SELECT 'ANDRAPRADESH' AS STATE;
	ELSE
		SELECT 'KARNATAKA' AS STATE;
	END IF;
END $$
DELIMITER ;

CALL GETSTATE(0);
DROP PROCEDURE IF EXISTS GETSTATE;

-- SWITCH
DELIMITER $$
CREATE PROCEDURE GETSTATE(
	IN ID INT
)
BEGIN
	CASE ID
		WHEN 3 THEN
			SELECT 'ANDRAPRADESH' AS STATE;
		WHEN 4 THEN
			SELECT 'KARNATAKA' AS STATE;
		ELSE
			SELECT 'TAMIL NADU' AS STATE;
	END CASE;
END $$
DELIMITER ;

CALL GETSTATE(0);

DELIMITER $$
CREATE PROCEDURE GETSTATE(
	IN ID INT
)
BEGIN
	CASE 
		WHEN ID=1 OR ID=2 THEN
			SELECT 'TAMILNADU' AS STATE;
		WHEN ID=3 THEN
			SELECT 'ANDRAPRADESH' AS STATE;
		ELSE
			SELECT 'KARNATAKA' AS STATE;
	END CASE;
END $$
DELIMITER ;

CALL GETSTATE(0);