USE FIRSTDATABASE;
-- SIMPLE LOOP:
DELIMITER $$
CREATE PROCEDURE LOOPDEMO1()
BEGIN
	DECLARE i INT;
    DECLARE STR VARCHAR(50);
    SET i = 1;
    SET STR = '';
LOOPLABEL: LOOP
	IF i > 10 THEN
		LEAVE LOOPLABEL;
	END IF;
	SET STR = CONCAT(STR,i,' ');
    SET i = i + 1;
END LOOP;
SELECT STR;
END $$
DELIMITER ;

CALL LOOPDEMO1();
DROP PROCEDURE if exists LOOPDEMO1;