USE FIRSTDATABASE;
-- WHILE LOOP
DELIMITER $$
CREATE PROCEDURE LOOPDEMO2()
BEGIN
	DECLARE i INT;
    DECLARE STR VARCHAR(50);
	SET i = 1;
    SET STR = '';
	WHILE i <= 10 DO
		SET STR = CONCAT(STR,i,' ');
		SET i = i + 1;
	END WHILE;
SELECT STR;
END $$
DELIMITER ;

CALL LOOPDEMO2();
DROP PROCEDURE LOOPDEMO2;