USE FIRSTDATABASE;
SELECT * FROM EMPLOYEE;
/*
	PARAMETERS
    - IN
    - OUT
    - INOUT
*/

-- PARAMETER_IN
DELIMITER $$
CREATE PROCEDURE JOBDESC_COUNT
(
	IN JDESC VARCHAR(20)
)
BEGIN
	DECLARE TOTAL INT DEFAULT 0;
    SELECT COUNT(ID) INTO TOTAL
    FROM EMPLOYEE
    WHERE JOB_DESC = JDESC;
    SELECT TOTAL;
END $$
DELIMITER ;

CALL JOBDESC_COUNT('ANALYST');
CALL JOBDESC_COUNT('ADMIN');
DROP PROCEDURE IF EXISTS JOBDESC_COUNT;