USE FIRSTDATABASE;

-- PARAMETER_IN_OUT
DELIMITER $$
CREATE PROCEDURE INCRCOUNTER(
	INOUT COUNTER INT,
    IN INCR INT
)
BEGIN 
	SET COUNTER = COUNTER + INCR;
END $$
DELIMITER ;

SET @COUNTER = 0;
CALL INCRCOUNTER(@COUNTER,2);
SELECT @COUNTER;
CALL INCRCOUNTER(@COUNTER,3);
SELECT @COUNTER;

DROP PROCEDURE IF EXISTS INCRCOUNTER;