USE FIRSTDATABASE;
SELECT * FROM EMPLOYEE;

-- PARAMETER_OUT
DELIMITER $$
CREATE PROCEDURE EMPLOYEE_COUNT
(
	IN JDESC VARCHAR(20),
    OUT TOTAL INT
)
BEGIN
    SELECT COUNT(ID) INTO TOTAL
    FROM EMPLOYEE
    WHERE JOB_DESC = JDESC;
END $$
DELIMITER ;

SET @TOTAL = 10;
CALL EMPLOYEE_COUNT('ANALYST',@TOTAL); -- SESSION VARIABLE
SELECT @TOTAL;
CALL EMPLOYEE_COUNT('ADMIN',@TOTAL);
SELECT @TOTAL;

DROP PROCEDURE IF EXISTS EMPLOYEE_COUNT;