USE FIRSTDATABASE;

-- SIGNAL - USER DEFINED ERROR
DELIMITER $$
CREATE PROCEDURE INSERTBRANCH(
	IN ID INT,
    IN B_NAME VARCHAR(20),
    IN ADDR VARCHAR(30)
)
BEGIN
	DECLARE CONTINUE HANDLER FOR 1062
    BEGIN
		SELECT CONCAT('DUPLICATE KEY',ID);
    END;
    IF CHAR_LENGTH(B_NAME) < 4 THEN
		SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'BRANCH NAME TOO SHORT';
	END IF;
    INSERT INTO BRANCH2 VALUES(ID,B_NAME,ADDR);
    SELECT * FROM BRANCH2;
END $$
DELIMITER ;

CALL INSERTBRANCH(1,'ABCD','XYZ');
DROP PROCEDURE IF EXISTS INSERTBRANCH;

-- ===================================================== --

-- RESIGNAL - 
DELIMITER $$
CREATE PROCEDURE INSERTBRANCH(
	IN ID INT,
    IN B_NAME VARCHAR(20),
    IN ADDR VARCHAR(30)
)
BEGIN
	DECLARE CONTINUE HANDLER FOR 1062
    RESIGNAL SET MESSAGE_TEXT = 'DUPLICATE KEY'; 
    INSERT INTO BRANCH2 VALUES(ID,B_NAME,ADDR);
    SELECT * FROM BRANCH2;
END $$
DELIMITER ;