-- ALTER COMMANDS
USE FIRST;
DESC EMPLOYEE1;

CREATE TABLE EMPLOYEE1(
	E_ID INT,
    E_NAME VARCHAR(20),
    JOBDESC VARCHAR(20),
    SALARY INT,
    PAN VARCHAR(10)
);

-- ADDDING NEW COLUMN
ALTER TABLE EMPLOYEE1
ADD COLUMN AGE INT;

ALTER TABLE EMPLOYEE1
DROP COLUMN AGE;

DESC EMPLOYEE1;

-- ADDING NEW CONSTRAINTS TO THE TABLE

-- PRIMARY KEY
ALTER TABLE EMPLOYEE1
ADD PRIMARY KEY(E_ID);

ALTER TABLE EMPLOYEE1
DROP PRIMARY KEY;

-- UNIQUE KEY 
ALTER TABLE EMPLOYEE1
ADD CONSTRAINT U_PAN UNIQUE(PAN);

ALTER TABLE EMPLOYEE1
DROP CONSTRAINT U_PAN;

-- CHECK CONSTRAINT
ALTER TABLE EMPLOYEE1
ADD CONSTRAINT C_SALARY CHECK(SALARY > 1000000);

ALTER TABLE EMPLOYEE1
DROP CONSTRAINT C_SALARY;

-- NOT NULL CONSTRAINT
ALTER TABLE EMPLOYEE1
MODIFY E_NAME VARCHAR(20) NOT NULL;

ALTER TABLE EMPLOYEE1
MODIFY E_NAME VARCHAR(20);

-- DEFAULT CONSTRAINT
ALTER TABLE EMPLOYEE1
ALTER JOBDESC SET DEFAULT 'UNASSIGNED';

ALTER TABLE EMPLOYEE1
ALTER JOBDESC DROP DEFAULT;

-- FOREIGN KEY
ALTER TABLE BRANCH
ADD CONSTRAINT FK_BRANCH_ID
FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEE1 (E_ID);

ALTER TABLE BRANCH
DROP CONSTRAINT FK_BRANCH_ID;

-- INDEX
ALTER TABLE EMPLOYEE1
ADD INDEX (EMP_NAME);

ALTER TABLE EMPLOYEE1
DROP INDEX EMP_NAME;
