CREATE DATABASE FIRSTDATABASE;
DROP DATABASE FIRSTDATABASE;

USE FIRSTDATABASE;

CREATE TABLE STUDENT(
	id INT PRIMARY KEY,
    name VARCHAR(20),
    gpa DECIMAL(3,2)
);

DROP TABLE STUDENT;

DESCRIBE STUDENT;

ALTER TABLE STUDENT ADD COLUMN DEPRTMENT VARCHAR(20);
ALTER TABLE STUDENT DROP COLUMN DEPRTMENT;

INSERT INTO STUDENT VALUES(1,"DHONI",8.7);
INSERT INTO STUDENT VALUES(2,"KOLHI",9.6);
INSERT INTO STUDENT VALUES(3,"RAINA",8.6),
	(4,"ROHIT",8.5),(5,"RAHUL",9.2);

SELECT * FROM STUDENT;    
SELECT ID,NAME FROM STUDENT;
SELECT GPA,NAME FROM STUDENT;
