USE FIRSTDATABASE;

-- ---------NOT NULL----------

CREATE TABLE EMPLOYEE2(
	ID INT NOT NULL,
    EMP_NAME VARCHAR(20),
    AGE INT
);

SELECT * FROM EMPLOYEE2;
DESC EMPLOYEE2;
DROP TABLE EMPLOYEE2;

-- ADD NOT NULL CONSTRAINT
ALTER TABLE EMPLOYEE2
MODIFY EMP_NAME VARCHAR(30) NOT NULL;

-- DROP NOT NULL CONSTRAINT 
ALTER TABLE EMPLOYEE2
MODIFY EMP_NAME VARCHAR(30);

-- -------------UNIQUE-----------------

CREATE TABLE EMPLOYEE2(
	ID INT,
    NAME VARCHAR(15),
    PH INT UNIQUE
);

SELECT * FROM EMPLOYEE2;
DESC EMPLOYEE2;
DROP TABLE EMPLOYEE2;

INSERT INTO EMPLOYEE2 VALUES(1,"RAM",28326374);
INSERT INTO EMPLOYEE2 VALUES(2,"RAJ",28326374);

-- ADD UNIQUE
ALTER TABLE EMPLOYEE2
-- ADD UNIQUE(PH);
ADD CONSTRAINT U_PH UNIQUE(PH);

-- DROP UNIQUE
ALTER TABLE EMPLOYEE2
DROP CONSTRAINT U_PH; 

-- ------------CHECK-------------------

CREATE TABLE EMPLOYEE2(
	ID INT,
    NAME VARCHAR(20),
    AGE INT,
    CHECK(AGE > 18)
);

SELECT * FROM EMPLOYEE2;
DESC EMPLOYEE2;
DROP TABLE EMPLOYEE2;

INSERT INTO EMPLOYEE2 VALUES(1,"RAJ",40);
INSERT INTO EMPLOYEE2 VALUES(2,"RAM",18);

-- ADD CHECK 
ALTER TABLE EMPLOYEE2
-- ADD CHECK (AGE > 18);
ADD CONSTRAINT CHK_AGE CHECK (AGE > 18);

-- DROP CHECK
ALTER TABLE EMPLOYEE2
DROP CONSTRAINT CHK_AGE;

-- ------------PRIMARY KEY---------------

CREATE TABLE EMPLOYEE2(
	ID INT,
    NAME VARCHAR(20),
    AGE INT,
    PRIMARY KEY(ID,NAME)
);

SELECT * FROM EMPLOYEE2;
DESC EMPLOYEE2;
DROP TABLE EMPLOYEE2;

INSERT INTO EMPLOYEE2 VALUES(1,"RAM",20);
INSERT INTO EMPLOYEE2 VALUES(1,"RAJ",21);
INSERT INTO EMPLOYEE2 VALUES(2,"RAM",22);

-- ADD PRIMARY KEY
ALTER TABLE EMPLOYEE2
ADD PRIMARY KEY(ID,NAME);

-- DROP PRIMARY KEY
ALTER TABLE EMPLOYEE2
DROP PRIMARY KEY;

-- ------------DEFAULT-------------- 

CREATE TABLE EMPLOYEE2(
	ID INT,
    USER VARCHAR(20) DEFAULT 'NEW USER',
    AGE INT
);

DESC EMPLOYEE2;
SELECT * FROM EMPLOYEE2;
DROP TABLE EMPLOYEE2;

INSERT INTO EMPLOYEE2 (ID,AGE) VALUES (1,7);
INSERT INTO EMPLOYEE2 VALUES (1,"RAJ",8);

-- ADD DEFAULT
ALTER TABLE EMPLOYEE2
ALTER USER SET DEFAULT 'NEW USER';

-- DROP DEFAULT
ALTER TABLE EMPLOYEE2
ALTER USER DROP DEFAULT;