USE FIRSTDATABASE;
CREATE TABLE EMPLOYEE2(
	ID INT,
    EMP_NAME VARCHAR(15),
    JOB_DESC VARCHAR(20),
    SALARY INT,
    PAN VARCHAR(10)
);

CREATE TABLE EMPLOYEE2(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    EMP_NAME VARCHAR(15) NOT NULL,
    JOB_DESC VARCHAR(20) DEFAULT 'UNASSIGNED',
    SALARY INT CHECK (SALARY > 100000),
    PAN VARCHAR(10) UNIQUE
);

DESC EMPLOYEE2;
SELECT * FROM EMPLOYEE2;
DROP TABLE EMPLOYEE2;

INSERT INTO EMPLOYEE2 VALUES ("RAM",999,"8687567");
INSERT INTO EMPLOYEE2(EMP_NAME,SALARY,PAN) VALUES ("RAM",100008,"987643423"),("RAJ",100001,"987649423");

-- PRIMARY KEY
ALTER TABLE EMPLOYEE2
ADD PRIMARY KEY AUTO_INCREMENT(ID);

ALTER TABLE EMPLOYEE2
DROP PRIMARY KEY;

-- NOT NULL
ALTER TABLE EMPLOYEE2
MODIFY EMP_NAME VARCHAR(20) NOT NULL;

ALTER TABLE EMPLOYEE2
MODIFY EMP_NAME VARCHAR(20);

-- DEFAULT
ALTER TABLE EMPLOYEE2
ALTER JOB_DESC SET DEFAULT 'UNASSIGNED';

ALTER TABLE EMPLOYEE2
ALTER JOB_DESC DROP DEFAULT;

-- CHECK
ALTER TABLE EMPLOYEE2
ADD CONSTRAINT CHK_SAL CHECK (SALARY > 100000);

ALTER TABLE EMPLOYEE2
DROP CONSTRAINT CHK_SAL;

-- UNIQUE
ALTER TABLE EMPLOYEE2
ADD CONSTRAINT UNI_PAN UNIQUE (PAN);

ALTER TABLE EMPLOYEE2
DROP CONSTRAINT UNI_PAN;
