USE FIRSTDATABASE;

CREATE TABLE EMPLOYEE1(
	ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(20),
    JOB_DESC VARCHAR(30),
    SALARY INT
);

INSERT INTO EMPLOYEE1 VALUES(1,"RAJ","ADMIN",1000000);
INSERT INTO EMPLOYEE1 VALUES(2,"HARINI","MANAGER",2500000);
INSERT INTO EMPLOYEE1 VALUES(3,"GEORGE","SALES",2000000);
INSERT INTO EMPLOYEE1 VALUES(4,"RAMYA","SALES",1300000);
INSERT INTO EMPLOYEE1 VALUES(5,"MEENA","HR",2000000);
INSERT INTO EMPLOYEE1 VALUES(6,"ASHOK","MANAGER",3000000);
INSERT INTO EMPLOYEE1 VALUES(7,"ABDUL","HR",2000000);
INSERT INTO EMPLOYEE1 VALUES(8,"RAMYA","ENGINEER",1000000);
INSERT INTO EMPLOYEE1 VALUES(9,"RAGHU","CEO",8000000);
INSERT INTO EMPLOYEE1 VALUES(10,"ARVIND","MANAGER",2800000);
INSERT INTO EMPLOYEE1 VALUES(11,"AKSHAY","ENGINEER",1000000);
INSERT INTO EMPLOYEE1 VALUES(12,"JOHN","ADMIN",2200000);
INSERT INTO EMPLOYEE1 VALUES(13,"ABINAYA","ENGINEER",2100000);

SELECT * FROM EMPLOYEE1;

-- [DISTINCT] UNIQUE ELEMENT FROM THE COLUMN

SELECT JOB_DESC FROM EMPLOYEE1;
SELECT DISTINCT JOB_DESC FROM EMPLOYEE1;

-- [ORDER BY] TO SORT TABLE BY CERTAIN COLUMN
-- ASCENDING DEFAULT [ASC]

SELECT * FROM EMPLOYEE1
ORDER BY EMP_NAME ASC;

SELECT * FROM EMPLOYEE1
ORDER BY EMP_NAME DESC;

SELECT * FROM EMPLOYEE1
ORDER BY SALARY;

SELECT * FROM EMPLOYEE1
ORDER BY SALARY,EMP_NAME;

SELECT * FROM EMPLOYEE1
WHERE JOB_DESC="MANAGER"
ORDER BY SALARY;

SELECT * FROM EMPLOYEE1
ORDER BY JOB_DESC; 

SELECT * FROM EMPLOYEE1
ORDER BY (CASE JOB_DESC
WHEN 'CEO' THEN 1
WHEN 'MANAGER' THEN 2
WHEN 'HR' THEN 3
WHEN 'ENGINEER' THEN 4
WHEN 'SALES' THEN 5
ELSE 100 END
),SALARY;