USE FIRSTDATABASE;

CREATE TABLE DEPARTMENT(
	ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(10)
);

CREATE TABLE EMPLOYEE3(
	ID INT NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(15),
    DEPT_ID INT
--  CONSTRAINT FK_BRANCH_ID FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(ID) 
);

ALTER TABLE EMPLOYEE3
ADD CONSTRAINT FK_BRANCH_ID
FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(ID);

ALTER TABLE EMPLOYEE3
DROP FOREIGN KEY FK_BRANCH_ID;

DESC EMPLOYEE3;
DESC DEPARTMENT;
DROP TABLE EMPLOYEE3;
DROP TABLE DEPARTMENT;
SELECT * FROM EMPLOYEE3;
SELECT * FROM DEPARTMENT;

INSERT INTO DEPARTMENT VALUES(1,"CSE"),(2,"IT"),(3,"ECE"),(4,"EEE"),(5,"MECH");

INSERT INTO EMPLOYEE3 VALUES (1,"RAM","MADURAI",1),(2,"SHAN","CHENNAI",4),
(3,"RAJ","TRICHY",5),(4,"TAMIL","KARUR",4);
INSERT INTO EMPLOYEE3 VALUES(5,"MONK","TIRUNALVELI",9); 