USE FIRSTDATABASE;
/*
CREATE TABLE EMPLOYEE1(
	ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(20),
    JOB_DESC VARCHAR(30),
    SALARY INT
);

INSERT INTO EMPLOYEE1 VALUES(1,"RAJ","ADMIN",1000000);
INSERT INTO EMPLOYEE1 VALUES(2,"HARINI","MANAGER",2500000);
INSERT INTO EMPLOYEE1 VALUES(3,"GEORGE","SALES",2000000);
INSERT INTO EMPLOYEE1 VALUES(4,"RAMYA","SALES",1300000);
INSERT INTO EMPLOYEE1 VALUES(5,"MEENA","HR",2000000);
INSERT INTO EMPLOYEE1 VALUES(6,"ASHOK","MANAGER",3000000);
INSERT INTO EMPLOYEE1 VALUES(7,"ABDUL","HR",2000000);
INSERT INTO EMPLOYEE1 VALUES(8,"RAMYA","ENGINEER",1000000);
INSERT INTO EMPLOYEE1 VALUES(9,"RAGHU","CEO",8000000);
INSERT INTO EMPLOYEE1 VALUES(10,"ARVIND","MANAGER",2800000);
INSERT INTO EMPLOYEE1 VALUES(11,"AKSHAY","ENGINEER",1000000);
INSERT INTO EMPLOYEE1 VALUES(12,"JOHN","ADMIN",2200000);
INSERT INTO EMPLOYEE1 VALUES(13,"ABINAYA","ENGINEER",2100000);
*/

SELECT * FROM EMPLOYEE1;

-- FUNCTIONS - PERFORMS A SPECIFIC TASK
-- AGGREGATE FUNCTION [***MAX,MIN,AVG,COUNT,SUM***]

-- MATH FUNCTIONS

SELECT COUNT(*) TOTAL -- alais name
FROM EMPLOYEE;

SELECT COUNT(*) NO_OF_MANAGERS -- alais name
FROM EMPLOYEE1
WHERE JOB_DESC="MANAGER";

SELECT AVG(SALARY) AVG_SALARY
FROM EMPLOYEE1
WHERE JOB_DESC="MANAGER";

SELECT SUM(SALARY) SUM_OF_ENGINEER_SALARY
FROM EMPLOYEE1
WHERE JOB_DESC="ENGINEER";

SELECT MAX(SALARY) 
FROM EMPLOYEE1;

SELECT MIN(SALARY) 
FROM EMPLOYEE1;

-- STRING FUNCTIONS

SELECT EMP_NAME,SALARY 
FROM EMPLOYEE1;

	-- UCASE
SELECT LCASE(EMP_NAME) NAME,SALARY 
FROM EMPLOYEE1;

SELECT EMP_NAME,CHAR_LENGTH(EMP_NAME) CHAR_COUNT
FROM EMPLOYEE1; 

SELECT EMP_NAME,CONCAT('RS.',SALARY) SALARY
FROM EMPLOYEE1;

SELECT EMP_NAME,CONCAT('RS.',FORMAT(SALARY,0)) SALARY
FROM EMPLOYEE1;

			 -- RIGHT
SELECT EMP_NAME,LEFT(JOB_DESC,3) FIRST_3_CHAR
FROM EMPLOYEE1;