USE FIRSTDATABASE;

SELECT * FROM EMPLOYEE1;

SELECT * FROM EMPLOYEE1
ORDER BY JOB_DESC;

SELECT JOB_DESC,AVG(SALARY) FROM EMPLOYEE1
GROUP BY JOB_DESC;

SELECT JOB_DESC,COUNT(ID) FROM EMPLOYEE1
GROUP BY JOB_DESC;

SELECT JOB_DESC,COUNT(ID) 
FROM EMPLOYEE1
GROUP BY JOB_DESC
ORDER BY JOB_DESC;

SELECT JOB_DESC,COUNT(ID) 
FROM EMPLOYEE1
GROUP BY JOB_DESC
HAVING COUNT(ID)>1
ORDER BY COUNT(ID) DESC;

SELECT JOB_DESC,COUNT(ID) 
FROM EMPLOYEE1
WHERE SALARY > 1500000
GROUP BY JOB_DESC
HAVING COUNT(ID)>1
ORDER BY JOB_DESC;