USE FIRSTDATABASE;

DROP TABLE BRANCH2;
DROP TABLE EMPLOYEE6;

CREATE TABLE BRANCH2(
	BRANCH_ID INT PRIMARY KEY AUTO_INCREMENT,
    BRANCH_NAME VARCHAR(20),
    ADDRESS VARCHAR(30)
);

CREATE TABLE EMPLOYEE6(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(20) NOT NULL,
    JOB_DESC VARCHAR(20),
    SALARY INT,
    BRANCH_ID INT,
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH2(BRANCH_ID)
    ON DELETE SET NULL
);

INSERT INTO BRANCH2 VALUES(1,"MADURAI","ANNA NAGAR"),(2,"TRICHY","KALPAKKAM"),(3,"CHENNAI","TIDLE PARK"),(4,"MUMBAI","WANKADE");
INSERT INTO BRANCH2 VALUES(5,"BENGULURU","CHINNASWAMY");

INSERT INTO EMPLOYEE6 VALUES(1,"RAJ","ADMIN",1000000,1);
INSERT INTO EMPLOYEE6 VALUES(2,"HARINI","MANAGER",2500000,3);
INSERT INTO EMPLOYEE6 VALUES(3,"GEORGE","SALES",2000000,2);
INSERT INTO EMPLOYEE6 VALUES(4,"RAMYA","SALES",1300000,3);
INSERT INTO EMPLOYEE6 VALUES(5,"MEENA","HR",2000000,2);
INSERT INTO EMPLOYEE6 VALUES(6,"ASHOK","MANAGER",3000000,1);
INSERT INTO EMPLOYEE6 VALUES(7,"ABDUL","HR",2000000,2);
INSERT INTO EMPLOYEE6 VALUES(8,"RAMYA","ENGINEER",1000000,3);
INSERT INTO EMPLOYEE6 VALUES(9,"RAGHU","CEO",8000000,1);
INSERT INTO EMPLOYEE6 VALUES(10,"ARVIND","MANAGER",2800000,2);
INSERT INTO EMPLOYEE6 VALUES(11,"AKSHAY","ENGINEER",1000000,3);
INSERT INTO EMPLOYEE6 VALUES(12,"JOHN","ADMIN",2200000,1);
INSERT INTO EMPLOYEE6 VALUES(13,"ABINAYA","ENGINEER",2100000,4);
INSERT INTO EMPLOYEE6 VALUES(14,"AKASH","ANALYST","1000000",4);

SELECT * FROM EMPLOYEE6;
SELECT * FROM BRANCH2;

DELETE FROM BRANCH2
WHERE BRANCH_ID = 4;

-- INNER JOIN ALIAS JOIN
SELECT E.ID,E.NAME,E.JOB_DESC,B.BRANCH_NAME
FROM EMPLOYEE6 AS E
INNER JOIN BRANCH2 AS B
ON E.BRANCH_ID = B.BRANCH_ID
ORDER BY E.ID;

-- LEFT JOIN
SELECT EMPLOYEE6.ID,EMPLOYEE6.NAME,EMPLOYEE6.JOB_DESC,BRANCH2.BRANCH_NAME
FROM EMPLOYEE6
LEFT JOIN BRANCH2
ON EMPLOYEE6.BRANCH_ID = BRANCH2.BRANCH_ID
ORDER BY EMPLOYEE6.ID;

-- RIGHT JOIN
SELECT EMPLOYEE6.ID,EMPLOYEE6.NAME,EMPLOYEE6.JOB_DESC,BRANCH2.BRANCH_NAME
FROM EMPLOYEE6
RIGHT JOIN BRANCH2
ON EMPLOYEE6.BRANCH_ID = BRANCH2.BRANCH_ID
ORDER BY EMPLOYEE6.ID;

-- CROSS JOIN
SELECT EMPLOYEE6.ID,EMPLOYEE6.NAME,EMPLOYEE6.JOB_DESC,BRANCH2.BRANCH_NAME
FROM EMPLOYEE6
CROSS JOIN BRANCH2;

-- WHERE CLASS
SELECT E.ID,E.NAME,E.JOB_DESC,B.BRANCH_NAME
FROM EMPLOYEE6 AS E,BRANCH2 AS B
WHERE E.BRANCH_ID = B.BRANCH_ID
ORDER BY E.ID;


-- BRANCH_NAME,EMP_COUNT

SELECT BRANCH2.BRANCH_NAME,COUNT(EMPLOYEE6.ID) AS EMP_COUNT
FROM BRANCH2
JOIN EMPLOYEE6
ON BRANCH2.BRANCH_ID = EMPLOYEE6.BRANCH_ID
GROUP BY EMPLOYEE6.BRANCH_ID;

