USE FIRSTDATABASE;

CREATE TABLE EMPLOYEES(
    EMPLOYEE_ID INT PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR(30),
    MANAGER_ID INT, -- Assuming MANAGER_ID is of type INT
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

INSERT INTO EMPLOYEES VALUES
    (1, 'RYA', NULL),  -- RYA DOESN'T HAVE A MANAGER
    (2, 'ALEX', 1),    -- ALEX'S MANAGER IS RYA(1)
    (3, 'JOHN', 1),    -- JOHN'S MANAGER IS RYA(1)
    (4, 'MAYA', 2),    -- MAYA'S MANAGER IS ALEX(2)
    (5, 'WICK', 3),    -- WICK'S MANAGER IS JOHN(3)
    (6, 'RAJU', 3),    -- RAJU'S MANAGER IS JOHN(3)
    (7, 'AARI', 2),    -- AARI'S MANAGER IS ALEX(2)
    (8, 'BALA', 3);    -- BALA'S MANAGER IS JOHN(3)
                           
SELECT E.EMPLOYEE_ID, 
	E.EMPLOYEE_NAME AS EMPLOYEE,
	M.EMPLOYEE_NAME AS MANAGER
FROM EMPLOYEES AS E
INNER JOIN EMPLOYEES AS M
ON M.EMPLOYEE_ID = E.MANAGER_ID;

-- ----------------------------------------------------------------------------

DROP TABLE EMPLOYEES;

CREATE TABLE EMPLOYEES(
    EMPLOYEE_ID INT PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR(30),
    MANAGER_ID INT, -- Assuming MANAGER_ID is of type INT
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

INSERT INTO EMPLOYEES VALUES
    (1, 'RYA', NULL),  -- RYA DOESN'T HAVE A MANAGER
    (2, 'ALEX', 1),    -- ALEX'S MANAGER IS RYA(1)
    (3, 'JOHN', 1),    -- JOHN'S MANAGER IS RYA(1)
    (4, 'MAYA', 2),    -- MAYA'S MANAGER IS ALEX(2)
    (5, 'WICK', 3),    -- WICK'S MANAGER IS JOHN(3)
    (6, 'RAJU', 3),    -- RAJU'S MANAGER IS JOHN(3)
    (7, 'AARI', 2),    -- AARI'S MANAGER IS ALEX(2)
    (8, 'BALA', 3);    -- BALA'S MANAGER IS JOHN(3)

-- Self-join to retrieve employees and their managers
SELECT E.EMPLOYEE_ID, 
	E.EMPLOYEE_NAME AS EMPLOYEE,
	M.EMPLOYEE_NAME AS MANAGER
FROM EMPLOYEES AS E
INNER JOIN EMPLOYEES AS M
ON M.EMPLOYEE_ID = E.MANAGER_ID;