USE FIRSTDATABASE;

CREATE TABLE BRANCH2(
	BRANCH_ID INT PRIMARY KEY AUTO_INCREMENT,
    BRANCH_NAME VARCHAR(20),
    ADDRESS VARCHAR(30)
);

CREATE TABLE EMPLOYEE6(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(20) NOT NULL,
    JOB_DESC VARCHAR(20),
    SALARY INT,
    BRANCH_ID INT,
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH2(BRANCH_ID)
    ON DELETE SET NULL
);

INSERT INTO BRANCH2 VALUES(1,"MADURAI","ANNA NAGAR"),(2,"TRICHY","KALPAKKAM"),(3,"CHENNAI","TIDLE PARK"),(4,"MUMBAI","WANKADE");
INSERT INTO BRANCH2 VALUES(5,"BENGULURU","CHINNASWAMY");

INSERT INTO EMPLOYEE6 VALUES(1,"RAJ","ADMIN",1000000,1);
INSERT INTO EMPLOYEE6 VALUES(2,"HARINI","MANAGER",2500000,3);
INSERT INTO EMPLOYEE6 VALUES(3,"GEORGE","SALES",2000000,2);
INSERT INTO EMPLOYEE6 VALUES(4,"RAMYA","SALES",1300000,3);
INSERT INTO EMPLOYEE6 VALUES(5,"MEENA","HR",2000000,2);
INSERT INTO EMPLOYEE6 VALUES(6,"ASHOK","MANAGER",3000000,1);
INSERT INTO EMPLOYEE6 VALUES(7,"ABDUL","HR",2000000,2);
INSERT INTO EMPLOYEE6 VALUES(8,"RAMYA","ENGINEER",1000000,3);
INSERT INTO EMPLOYEE6 VALUES(9,"RAGHU","CEO",8000000,1);
INSERT INTO EMPLOYEE6 VALUES(10,"ARVIND","MANAGER",2800000,2);
INSERT INTO EMPLOYEE6 VALUES(11,"AKSHAY","ENGINEER",1000000,3);
INSERT INTO EMPLOYEE6 VALUES(12,"JOHN","ADMIN",2200000,1);
INSERT INTO EMPLOYEE6 VALUES(13,"ABINAYA","ENGINEER",2100000,4);
INSERT INTO EMPLOYEE6 VALUES(14,"AKASH","ANALYST","1000000",4);

SELECT * FROM EMPLOYEE6;
SELECT * FROM BRANCH2;

-- EMPLOYEE FROM CHENNAI BRANCH
SELECT * FROM EMPLOYEE6
WHERE BRANCH_ID = (SELECT BRANCH_ID FROM BRANCH2
WHERE BRANCH_NAME = "CHENNAI");

-- EMPLOYEE SALARY WITH MIN SALARY
SELECT * FROM EMPLOYEE6
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEE6);


-- ----------EXISTS used with subquery------------
-- BRANCHES COINTAINING ONLY ONE ADMIN
SELECT BRANCH_ID,BRANCH_NAME FROM BRANCH2
WHERE EXISTS (
SELECT * FROM EMPLOYEE6 
WHERE JOB_DESC="ADMIN" AND BRANCH2.BRANCH_ID = EMPLOYEE6.BRANCH_ID
);

SELECT BRANCH_ID, BRANCH_NAME FROM BRANCH
WHERE BRANCH_ID IN
(SELECT BRANCH_ID FROM EMPLOYEE1
WHERE JOBDESC = 'ADMIN');

-- ANY
-- BRANCH INFO IN WHICH ANY EMPLOYEE GETS MORE THAN 25L
SELECT * FROM BRANCH2
WHERE BRANCH_ID = ANY(
SELECT BRANCH_ID FROM EMPLOYEE6 
WHERE SALARY > 2500000);

SELECT * FROM BRANCH
WHERE BRANCH_ID IN
(SELECT BRANCH_ID FROM EMPLOYEE1
WHERE SALARY > 2500000);

-- ALL
-- EMPLOYEE NOT WORKING I CHENNAI OR COIMBATORE
SELECT * FROM EMPLOYEE6
WHERE BRANCH_ID <> ALL(
SELECT BRANCH_ID FROM BRANCH2
WHERE BRANCH_NAME IN ("CHENNAI","MADURAI")
);

SELECT * FROM EMPLOYEE1
WHERE BRANCH_ID NOT IN
(SELECT BRANCH_ID FROM BRANCH
WHERE BRANCH_NAME IN ('CHENNAI', 'COIMBATORE'));

