-- ------------ UNION --------------

CREATE TABLE CLIENT(
	CLIENT_ID INT PRIMARY KEY AUTO_INCREMENT, 
    CONTINENT VARCHAR(20),
    LOCATION VARCHAR(20)
);
DROP TABLE CLIENT;

INSERT INTO CLIENT VALUES(1,"ASIA","DUBAI");
INSERT INTO CLIENT VALUES(2,"AUSTRALIA","MELBORNE");
INSERT INTO CLIENT VALUES(3,"AFRICA","ZIMBAWE");

SELECT * FROM CLIENT;
SELECT * FROM BRANCH2;

SELECT * FROM CLIENT
UNION
SELECT * FROM BRANCH2;

SELECT * FROM BRANCH2
UNION ALL
SELECT * FROM CLIENT;