USE FIRSTDATABASE;

SELECT * FROM EMPLOYEE6;
SELECT * FROM BRANCH2;

-- VIEW 
-- CREATE VIEW
CREATE VIEW EMP_BR
AS
SELECT E.ID,E.NAME,E.JOB_DESC,B.BRANCH_NAME
FROM EMPLOYEE6 AS E
INNER JOIN BRANCH2 AS B
ON B.BRANCH_ID = E.BRANCH_ID
ORDER BY E.ID;

-- REPLACE VIEW
CREATE OR REPLACE VIEW EMP_BR
AS
SELECT E.ID,E.NAME,E.JOB_DESC,B.BRANCH_NAME
FROM EMPLOYEE6 AS E
INNER JOIN BRANCH2 AS B
ON B.BRANCH_ID = E.BRANCH_ID
ORDER BY E.ID;

-- DROP VIEW
DROP VIEW EMP_BR;

SELECT * FROM EMP_BR;

SELECT * FROM EMP_BR
WHERE JOB_DESC = "MANAGER";