USE FIRSTDATABASE;

CREATE TABLE EMPLOYEE(
	ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(20),
    JOB_DESC VARCHAR(30),
    SALARY INT
);

INSERT INTO EMPLOYEE VALUES(1,"RAJ","ADMIN",1000000);
INSERT INTO EMPLOYEE VALUES(2,"HARINI","MANAGER",2500000);
INSERT INTO EMPLOYEE VALUES(3,"GEORGE","SALES",2000000);
INSERT INTO EMPLOYEE VALUES(4,"RAMYA","SALES",1300000);
INSERT INTO EMPLOYEE VALUES(5,"MEENA","HR",2000000);
INSERT INTO EMPLOYEE VALUES(6,"ASHOK","MANAGER",3000000);
INSERT INTO EMPLOYEE VALUES(7,"ABDUL","HR",2000000);
INSERT INTO EMPLOYEE VALUES(8,"RAMYA","ENGINEER",1000000);
INSERT INTO EMPLOYEE VALUES(9,"RAGHU","CEO",8000000);
INSERT INTO EMPLOYEE VALUES(10,"ARVIND","MANAGER",2800000);
INSERT INTO EMPLOYEE VALUES(11,"AKSHAY","ENGINEER",1000000);
INSERT INTO EMPLOYEE VALUES(12,"JOHN","ADMIN",2200000);
INSERT INTO EMPLOYEE VALUES(13,"ABINAYA","ENGINEER",2100000);

SELECT * FROM EMPLOYEE;
-- ------------------------------------------------------
SELECT * FROM EMPLOYEE 
WHERE EMP_NAME="RAMYA";

SELECT * FROM EMPLOYEE 
WHERE SALARY > 2100000;

SELECT ID,EMP_NAME FROM EMPLOYEE
WHERE SALARY > 1000000;

SELECT * FROM EMPLOYEE
WHERE SALARY < 2600000 AND JOB_DESC = "MANAGER";
-- ------------------------------------------------------

-- -----------------------------------------
SELECT * FROM EMPLOYEE
WHERE JOB_DESC = "HR" OR JOB_DESC = "SALES";
-- 
SELECT * FROM EMPLOYEE
WHERE JOB_DESC IN ("HR","SALES");
-- -----------------------------------------

-- -----------------------------------------
SELECT * FROM EMPLOYEE
WHERE JOB_DESC <> "CEO" AND JOB_DESC <> "MANAGER";
--
SELECT * FROM EMPLOYEE
WHERE JOB_DESC NOT IN ("CEO","MANAGER");
-- -----------------------------------------

-- -----------------------------------------
SELECT * FROM EMPLOYEE
WHERE SALARY BETWEEN 1000000 AND 2000000;
-- between for range purpose.......

SELECT * FROM EMPLOYEE
LIMIT 5;

SELECT * FROM EMPLOYEE
WHERE SALARY BETWEEN 1000000 AND 2000000
LIMIT 5;
-- -----------------------------------------

-- LIKE (KEYWORDS)
-- WILDCARDS % (ZERO OR MORE CHARACTERS) _ (ONE CHARACTER)

-- ------------------------------------------

SELECT * FROM EMPLOYEE
WHERE EMP_NAME LIKE 'A%';

SELECT * FROM EMPLOYEE
WHERE EMP_NAME NOT LIKE 'A%';

SELECT * FROM EMPLOYEE
WHERE EMP_NAME LIKE '%A';

SELECT * FROM EMPLOYEE
WHERE EMP_NAME LIKE '%I%';

-- To select the particular letter (_)

SELECT * FROM EMPLOYEE
WHERE EMP_NAME LIKE '__I%';

SELECT * FROM EMPLOYEE
WHERE EMP_NAME LIKE '__IN%';

-- to check wheather the % is present int table use [/] (Escape Sequence)

SELECT * FROM EMPLOYEE
WHERE EMP_NAME LIKE '__I\%';

SELECT * FROM EMPLOYEE
WHERE EMP_NAME LIKE 'NULL';

SELECT * FROM EMPLOYEE
WHERE SALARY LIKE '1%';

-- -------------------------------------------------------
-- UPDATE THE TABLE CONTENT
-- SET SQL_SAFE_UPDATES = 0;
-- -------------------------------------------------------

SET SQL_SAFE_UPDATES = 0;

UPDATE EMPLOYEE
SET JOB_DESC = "MANAGER";
-- it will change the  entire job_desc into ANALYST... use WHERE class.

UPDATE EMPLOYEE
SET JOB_DESC = "ANALYST"
WHERE JOB_DESC = "ENGINEER";

UPDATE  EMPLOYEE
SET JOB_DESC = "MARKETING", SALARY = 2500000
WHERE JOB_DESC = "SALES";

UPDATE EMPLOYEE
SET SALARY = 3000000
WHERE ID = 5;
-- -------------------------------------------------------

DELETE FROM EMPLOYEE
WHERE ID = 12;

-- -------------------------------------------------------
-- USING MULTIPLE TABLE
SELECT E.E_ID, E.E_NAME, E.JOBDESC, B.BRANCH_NAME
FROM EMPLOYEE AS E, BRANCH AS B
WHERE E.BRANCH_ID = B.BRANCH_ID
ORDER BY E.E_ID; 
